### ISSUE TITLE
CSS 내 이미지 경로 수정해주세요.

### ISSUE THREAD

**Issue by damduck2** [toriuri/awesomestory#29]
기존
../image/contents/image-girl@2x.png
../image/contents/image-boy@2x.png
../image/contents/image-daddy@2x.png
../image/contents/image-mom@2x.png
../image/contents/image-etc@2x.png

변경
../image/my-name-ran-away/image-girl@2x.png
../image/my-name-ran-away/image-boy@2x.png
../image/my-name-ran-away/image-daddy@2x.png
../image/my-name-ran-away/image-mom@2x.png
../image/my-name-ran-away/image-etc@2x.png

위 이미지들은 '내이름이 도망갔어' 전용 이미지라서 명확하게 구분해 놨어요~
다음 책도 추가될거라서요.

**Comment by toriuri** [comment]
수정완료
